### ISSUE TITLE
Releasing a build

### ISSUE THREAD

**Issue by gdimoff** [6eero/NewPass#1]
Hey,

I've just tested your app and it looks great on my Android. Do you plan to release prebuild version ? If you are interested I can list it on my open source repo at https://openapk.net/ so other people can try it !

**Comment by 6eero** [comment]
Yes sure. I still need to implement a few more functions, then I will be able to release the prebuilt version

**Comment by 6eero** [comment]
Done, I released it!

**Comment by IzzySoft** [comment]
@6eero please take care [for versioning](https://github.com/6eero/NewPass/blob/master/app/build.gradle.kts#L13), too! This is how the APK at v1.1.0 identifies:

    package: name='com.gero.newpass' versionCode='1' versionName='1.0'

it should have been `versionCode='2'` and `versionName='1.1.0'` (`versionCode` is what Android uses internally to tell versions apart – so in the current situation, v1.1.0 would not be considered an update to the previous version as the code didn't change; `versionName` is what is displayed to the human who then mentions it when reporting something to you). So you could never tell which version they talk about, as they all look the same…

**Comment by IzzySoft** [comment]
PS, while I'm here, my scanner also reported

    ! repo/com.gero.newpass_1.apk contains signature block blobs: 0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)

which can be easily avoided:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains.

Thanks in advance!

**Comment by 6eero** [comment]
> @6eero please take care [for versioning](https://github.com/6eero/NewPass/blob/master/app/build.gradle.kts#L13), too! This is how the APK at v1.1.0 identifies:
> 
> ```
> package: name='com.gero.newpass' versionCode='1' versionName='1.0'
> ```
> 
> it should have been `versionCode='2'` and `versionName='1.1.0'` (`versionCode` is what Android uses internally to tell versions apart – so in the current situation, v1.1.0 would not be considered an update to the previous version as the code didn't change; `versionName` is what is displayed to the human who then mentions it when reporting something to you). So you could never tell which version they talk about, as they all look the same…

Thanks, I didn't know that. I'm still a beginner. So, for every release I publish, do I need to increment the `versionCode` and update the `versionName` to match the version of the release I'm deploying? Right?

**Comment by 6eero** [comment]
Thank you! i'll do it!

**Comment by IzzySoft** [comment]
Worked out fine :partying_face: And thanks for adding the badge! :star_struck:
