### ISSUE TITLE
Fastlane improvements

### ISSUE THREAD

**Issue by IzzySoft** [6eero/NewPass#13]
Thanks for adding Fastlane structures! Could you please slightly adjust `full_description.txt`? A simple newline (empty line) before the bullet-point list would make it render perfectly as Markdown. You could also add an introductional paragraph:

> NewPass is a secure password management application designed to generate and store strong passwords locally on your device. With NewPass, you can create highly secure passwords for your accounts and services without the need to remember them.

(remember to separate that from the "Key features" by an empty line as well). If you wish, you can also use simply HTML formatting, e.g. enclosing "Key features" like this: `<b>Key Features:</b>`. Optionally, you can make it fully HTML:

```html
<p><i>NewPass</i> is a secure password management application designed to generate and store strong passwords locally on your device. With NewPass, you can create highly secure passwords for your accounts and services without the need to remember them.</p><p><br><b>Key Features:</b></p><ul><li><b>Password Generation:</b> NewPass provides a robust password generator that allows you to create complex and secure passwords tailored to your specific requirements. You can customize the length and the character set (Uppercase, Numbers and Special).</li><li><b>Local Storage:</b> Your passwords are stored locally on your device, ensuring complete privacy and control over your data. NewPass does not store any passwords on external servers, minimizing the risk of unauthorized access (If you uninstall the app, your password are lost!).</li><li><b>AES Encryption:</b> NewPass encrypts all stored passwords using Advanced Encryption Standard (AES) with Cipher Block Chaining (CBC) mode before saving them in the local database.</li><li><b>User-Friendly Interface:</b> NewPass features an intuitive and user-friendly interface, making it easy to generate, view, and manage your passwords. The app offers convenient options for copying passwords to the clipboard and securely sharing them with other applications.</li></ul>
```

(I've put that into a single line to prevent fdroid from replacing each line break by `<br>`, which it loves to do otherwise)

**Comment by 6eero** [comment]
Done!

**Comment by IzzySoft** [comment]
Thanks a lot!

**Comment by IzzySoft** [comment]
PS: monthly quality checker just complained:

    ! com.gero.newpass/en-US/changelogs/13.txt has 943 chars

Fastlane limit there is 500 chars – and everything behind that is simply cut off, even mid-word. I've just manually truncated it in a more sane manner this time, but please take care for future updates. Thanks!
