### ISSUE TITLE
dpi settings

### ISSUE THREAD

**Issue by Danielikto** [6eero/NewPass#2]
![Screenshot_2024-03-26-09-34-22-839_com gero newpass](https://github.com/6eero/NewPass/assets/10320929/431ca5e3-3340-440a-86c7-528f840c15e0)
![Screenshot_2024-03-26-09-34-27-877_com gero newpass](https://github.com/6eero/NewPass/assets/10320929/a0d5903f-f7eb-43dc-82f1-f37021b796b9)

**Comment by 6eero** [comment]
Thank you for reporting, I will fix it in the next update.

**Comment by 6eero** [comment]
Fixed it! Let me know if it's solved

**Comment by Danielikto** [comment]
Okay, it's solved now.
![Screenshot_2024-03-27-16-56-46-570_com gero newpass](https://github.com/6eero/NewPass/assets/10320929/f3f0ff48-58a9-42cd-a652-fabb720bb415)
![Screenshot_2024-03-27-16-56-52-267_com gero newpass](https://github.com/6eero/NewPass/assets/10320929/47e7a512-9146-44ae-aaf8-13d2ef36386e)
