### ISSUE TITLE
Permission question

### ISSUE THREAD

**Issue by IzzySoft** [6eero/NewPass#35]
May I ask what `android.permission.READ_EXTERNAL_STORAGE` (and WRITE) are needed for? With Android-7 being the minimal supported Android version, wouldn't SAF (Storage Access Framework) being more fitting to access the database file(s)?

**Comment by 6eero** [comment]
You're right, I didn't know they weren't needed. I've just committed the changes removing them. Thanks!

**Comment by IzzySoft** [comment]
Thanks!
