### ISSUE TITLE
security issues

### ISSUE THREAD

**Issue by obfusk** [6eero/NewPass#4]
Hi! I noticed the following:

`GeneratePasswordViewModel.generateRandomPassword()` uses `java.util.Random` -- which is not cryptographically secure -- instead of `java.security.SecureRandom`.

`EncryptionHelper` logs plaintext and keys; understandable for debugging but not something that should occur on users' devices.

(Additionally, I noticed the typo "lenght" a few times.)

**Comment by 6eero** [comment]
Fixed it, thank you 🙏🏻
