### ISSUE TITLE
F-Droid listing

### ISSUE THREAD

**Issue by IzzySoft** [6eero/NewPass#46]
I see your app reached F-Droid.org now – and your Readme now links to both, F-Droid *and* IzzyOnDroid. I take it you want to keep your app at IzzyOnDroid then? Just asking to make sure it was not an oversight. Due to the APK size being beyond 15 MB, IzzyOnDroid can currently only keep a single version btw.

**Comment by 6eero** [comment]
Yes, I would like to have it both on F-Droid and IzzyOnDroid

**Comment by IzzySoft** [comment]
Marked it as such then, thanks!
