### ISSUE TITLE
Password complexity

### ISSUE THREAD

**Issue by pabloscloud** [6eero/NewPass#7]
Include uppercase and numbers by default.

Use at least 14 characters.

Why 14? Strength testing tools rank the complexity as 'centuries' when trying the generated passwords from your app with uppercase and numbers using 14 but not less characters.

**Comment by 6eero** [comment]
Done! I didn't set the password requirement to be at least 14 characters because some users might want to store shorter passwords. However, I still increased the maximum length and set the generation seekbar to start from 14 instead of 8
